// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.12.3
// source: example.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ShopifyAuthRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Name of the shop
	Shop string `protobuf:"bytes,1,opt,name=shop,proto3" json:"shop,omitempty"`
}

func (x *ShopifyAuthRequest) Reset() {
	*x = ShopifyAuthRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_example_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShopifyAuthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShopifyAuthRequest) ProtoMessage() {}

func (x *ShopifyAuthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_example_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShopifyAuthRequest.ProtoReflect.Descriptor instead.
func (*ShopifyAuthRequest) Descriptor() ([]byte, []int) {
	return file_example_proto_rawDescGZIP(), []int{0}
}

func (x *ShopifyAuthRequest) GetShop() string {
	if x != nil {
		return x.Shop
	}
	return ""
}

// Contains successful or failed login attempt
type Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Success response
	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *Response) Reset() {
	*x = Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_example_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_example_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_example_proto_rawDescGZIP(), []int{1}
}

func (x *Response) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type ShopifyAuthCallbackRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Name of the shop
	Shop string `protobuf:"bytes,1,opt,name=shop,proto3" json:"shop,omitempty"`
	// Authorization code sent from Shopify
	Code string `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	// HMAC signature to make sure everything was sent by shopify
	Hmac string `protobuf:"bytes,3,opt,name=hmac,proto3" json:"hmac,omitempty"`
	// Timestamp sent by Shopify
	Timestamp int32 `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
}

func (x *ShopifyAuthCallbackRequest) Reset() {
	*x = ShopifyAuthCallbackRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_example_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShopifyAuthCallbackRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShopifyAuthCallbackRequest) ProtoMessage() {}

func (x *ShopifyAuthCallbackRequest) ProtoReflect() protoreflect.Message {
	mi := &file_example_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShopifyAuthCallbackRequest.ProtoReflect.Descriptor instead.
func (*ShopifyAuthCallbackRequest) Descriptor() ([]byte, []int) {
	return file_example_proto_rawDescGZIP(), []int{2}
}

func (x *ShopifyAuthCallbackRequest) GetShop() string {
	if x != nil {
		return x.Shop
	}
	return ""
}

func (x *ShopifyAuthCallbackRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *ShopifyAuthCallbackRequest) GetHmac() string {
	if x != nil {
		return x.Hmac
	}
	return ""
}

func (x *ShopifyAuthCallbackRequest) GetTimestamp() int32 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type ShopifyDataSyncRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ShopifyDataSyncRequest) Reset() {
	*x = ShopifyDataSyncRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_example_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShopifyDataSyncRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShopifyDataSyncRequest) ProtoMessage() {}

func (x *ShopifyDataSyncRequest) ProtoReflect() protoreflect.Message {
	mi := &file_example_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShopifyDataSyncRequest.ProtoReflect.Descriptor instead.
func (*ShopifyDataSyncRequest) Descriptor() ([]byte, []int) {
	return file_example_proto_rawDescGZIP(), []int{3}
}

type ShopifyDataSyncResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Products
	Result string `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *ShopifyDataSyncResponse) Reset() {
	*x = ShopifyDataSyncResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_example_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShopifyDataSyncResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShopifyDataSyncResponse) ProtoMessage() {}

func (x *ShopifyDataSyncResponse) ProtoReflect() protoreflect.Message {
	mi := &file_example_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShopifyDataSyncResponse.ProtoReflect.Descriptor instead.
func (*ShopifyDataSyncResponse) Descriptor() ([]byte, []int) {
	return file_example_proto_rawDescGZIP(), []int{4}
}

func (x *ShopifyDataSyncResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

type Empty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Empty) Reset() {
	*x = Empty{}
	if protoimpl.UnsafeEnabled {
		mi := &file_example_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_example_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_example_proto_rawDescGZIP(), []int{5}
}

var File_example_proto protoreflect.FileDescriptor

var file_example_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x02, 0x76, 0x31, 0x22, 0x28, 0x0a, 0x12, 0x53, 0x68, 0x6f, 0x70, 0x69, 0x66, 0x79, 0x41, 0x75,
	0x74, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x68, 0x6f,
	0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x73, 0x68, 0x6f, 0x70, 0x22, 0x24, 0x0a,
	0x08, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63,
	0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63,
	0x65, 0x73, 0x73, 0x22, 0x76, 0x0a, 0x1a, 0x53, 0x68, 0x6f, 0x70, 0x69, 0x66, 0x79, 0x41, 0x75,
	0x74, 0x68, 0x43, 0x61, 0x6c, 0x6c, 0x62, 0x61, 0x63, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x68, 0x6f, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x73, 0x68, 0x6f, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x68, 0x6d, 0x61,
	0x63, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x68, 0x6d, 0x61, 0x63, 0x12, 0x1c, 0x0a,
	0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x22, 0x18, 0x0a, 0x16, 0x53,
	0x68, 0x6f, 0x70, 0x69, 0x66, 0x79, 0x44, 0x61, 0x74, 0x61, 0x53, 0x79, 0x6e, 0x63, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x31, 0x0a, 0x17, 0x53, 0x68, 0x6f, 0x70, 0x69, 0x66, 0x79,
	0x44, 0x61, 0x74, 0x61, 0x53, 0x79, 0x6e, 0x63, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x07, 0x0a, 0x05, 0x45, 0x6d, 0x70, 0x74,
	0x79, 0x32, 0xad, 0x03, 0x0a, 0x0e, 0x53, 0x68, 0x6f, 0x70, 0x69, 0x66, 0x79, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x12, 0x2e, 0x0a, 0x04, 0x41, 0x75, 0x74, 0x68, 0x12, 0x16, 0x2e, 0x76,
	0x31, 0x2e, 0x53, 0x68, 0x6f, 0x70, 0x69, 0x66, 0x79, 0x41, 0x75, 0x74, 0x68, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x0c, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x00, 0x12, 0x2f, 0x0a, 0x08, 0x4e, 0x6f, 0x52, 0x65, 0x74, 0x75, 0x72, 0x6e,
	0x12, 0x16, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x68, 0x6f, 0x70, 0x69, 0x66, 0x79, 0x41, 0x75, 0x74,
	0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x09, 0x2e, 0x76, 0x31, 0x2e, 0x45, 0x6d,
	0x70, 0x74, 0x79, 0x22, 0x00, 0x12, 0x3e, 0x0a, 0x0c, 0x41, 0x75, 0x74, 0x68, 0x43, 0x61, 0x6c,
	0x6c, 0x62, 0x61, 0x63, 0x6b, 0x12, 0x1e, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x68, 0x6f, 0x70, 0x69,
	0x66, 0x79, 0x41, 0x75, 0x74, 0x68, 0x43, 0x61, 0x6c, 0x6c, 0x62, 0x61, 0x63, 0x6b, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0c, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x47, 0x0a, 0x08, 0x44, 0x61, 0x74, 0x61, 0x53, 0x79, 0x6e,
	0x63, 0x12, 0x1a, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x68, 0x6f, 0x70, 0x69, 0x66, 0x79, 0x44, 0x61,
	0x74, 0x61, 0x53, 0x79, 0x6e, 0x63, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e,
	0x76, 0x31, 0x2e, 0x53, 0x68, 0x6f, 0x70, 0x69, 0x66, 0x79, 0x44, 0x61, 0x74, 0x61, 0x53, 0x79,
	0x6e, 0x63, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x30, 0x01, 0x12, 0x53,
	0x0a, 0x14, 0x44, 0x61, 0x74, 0x61, 0x53, 0x79, 0x6e, 0x63, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d,
	0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x12, 0x1a, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x68, 0x6f, 0x70,
	0x69, 0x66, 0x79, 0x44, 0x61, 0x74, 0x61, 0x53, 0x79, 0x6e, 0x63, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x68, 0x6f, 0x70, 0x69, 0x66, 0x79, 0x44,
	0x61, 0x74, 0x61, 0x53, 0x79, 0x6e, 0x63, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x00, 0x28, 0x01, 0x12, 0x5c, 0x0a, 0x1b, 0x44, 0x61, 0x74, 0x61, 0x53, 0x79, 0x6e, 0x63, 0x53,
	0x74, 0x72, 0x65, 0x61, 0x6d, 0x42, 0x69, 0x44, 0x69, 0x72, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x61, 0x6c, 0x12, 0x1a, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x68, 0x6f, 0x70, 0x69, 0x66, 0x79, 0x44,
	0x61, 0x74, 0x61, 0x53, 0x79, 0x6e, 0x63, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b,
	0x2e, 0x76, 0x31, 0x2e, 0x53, 0x68, 0x6f, 0x70, 0x69, 0x66, 0x79, 0x44, 0x61, 0x74, 0x61, 0x53,
	0x79, 0x6e, 0x63, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x28, 0x01, 0x30,
	0x01, 0x42, 0x07, 0x5a, 0x05, 0x2e, 0x2f, 0x3b, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_example_proto_rawDescOnce sync.Once
	file_example_proto_rawDescData = file_example_proto_rawDesc
)

func file_example_proto_rawDescGZIP() []byte {
	file_example_proto_rawDescOnce.Do(func() {
		file_example_proto_rawDescData = protoimpl.X.CompressGZIP(file_example_proto_rawDescData)
	})
	return file_example_proto_rawDescData
}

var file_example_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_example_proto_goTypes = []interface{}{
	(*ShopifyAuthRequest)(nil),         // 0: v1.ShopifyAuthRequest
	(*Response)(nil),                   // 1: v1.Response
	(*ShopifyAuthCallbackRequest)(nil), // 2: v1.ShopifyAuthCallbackRequest
	(*ShopifyDataSyncRequest)(nil),     // 3: v1.ShopifyDataSyncRequest
	(*ShopifyDataSyncResponse)(nil),    // 4: v1.ShopifyDataSyncResponse
	(*Empty)(nil),                      // 5: v1.Empty
}
var file_example_proto_depIdxs = []int32{
	0, // 0: v1.ShopifyService.Auth:input_type -> v1.ShopifyAuthRequest
	0, // 1: v1.ShopifyService.NoReturn:input_type -> v1.ShopifyAuthRequest
	2, // 2: v1.ShopifyService.AuthCallback:input_type -> v1.ShopifyAuthCallbackRequest
	3, // 3: v1.ShopifyService.DataSync:input_type -> v1.ShopifyDataSyncRequest
	3, // 4: v1.ShopifyService.DataSyncStreamClient:input_type -> v1.ShopifyDataSyncRequest
	3, // 5: v1.ShopifyService.DataSyncStreamBiDirectional:input_type -> v1.ShopifyDataSyncRequest
	1, // 6: v1.ShopifyService.Auth:output_type -> v1.Response
	5, // 7: v1.ShopifyService.NoReturn:output_type -> v1.Empty
	1, // 8: v1.ShopifyService.AuthCallback:output_type -> v1.Response
	4, // 9: v1.ShopifyService.DataSync:output_type -> v1.ShopifyDataSyncResponse
	4, // 10: v1.ShopifyService.DataSyncStreamClient:output_type -> v1.ShopifyDataSyncResponse
	4, // 11: v1.ShopifyService.DataSyncStreamBiDirectional:output_type -> v1.ShopifyDataSyncResponse
	6, // [6:12] is the sub-list for method output_type
	0, // [0:6] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_example_proto_init() }
func file_example_proto_init() {
	if File_example_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_example_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ShopifyAuthRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_example_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_example_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ShopifyAuthCallbackRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_example_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ShopifyDataSyncRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_example_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ShopifyDataSyncResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_example_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Empty); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_example_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_example_proto_goTypes,
		DependencyIndexes: file_example_proto_depIdxs,
		MessageInfos:      file_example_proto_msgTypes,
	}.Build()
	File_example_proto = out.File
	file_example_proto_rawDesc = nil
	file_example_proto_goTypes = nil
	file_example_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// ShopifyServiceClient is the client API for ShopifyService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ShopifyServiceClient interface {
	// Shopify oauth
	Auth(ctx context.Context, in *ShopifyAuthRequest, opts ...grpc.CallOption) (*Response, error)
	NoReturn(ctx context.Context, in *ShopifyAuthRequest, opts ...grpc.CallOption) (*Empty, error)
	// Shopify after auth callback
	AuthCallback(ctx context.Context, in *ShopifyAuthCallbackRequest, opts ...grpc.CallOption) (*Response, error)
	// Shopify data sync request stream server
	DataSync(ctx context.Context, in *ShopifyDataSyncRequest, opts ...grpc.CallOption) (ShopifyService_DataSyncClient, error)
	// Shopify data sync request steam client
	DataSyncStreamClient(ctx context.Context, opts ...grpc.CallOption) (ShopifyService_DataSyncStreamClientClient, error)
	// Shopify data sync request stream bi-directional
	DataSyncStreamBiDirectional(ctx context.Context, opts ...grpc.CallOption) (ShopifyService_DataSyncStreamBiDirectionalClient, error)
}

type shopifyServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewShopifyServiceClient(cc grpc.ClientConnInterface) ShopifyServiceClient {
	return &shopifyServiceClient{cc}
}

func (c *shopifyServiceClient) Auth(ctx context.Context, in *ShopifyAuthRequest, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/v1.ShopifyService/Auth", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shopifyServiceClient) NoReturn(ctx context.Context, in *ShopifyAuthRequest, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/v1.ShopifyService/NoReturn", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shopifyServiceClient) AuthCallback(ctx context.Context, in *ShopifyAuthCallbackRequest, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/v1.ShopifyService/AuthCallback", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shopifyServiceClient) DataSync(ctx context.Context, in *ShopifyDataSyncRequest, opts ...grpc.CallOption) (ShopifyService_DataSyncClient, error) {
	stream, err := c.cc.NewStream(ctx, &_ShopifyService_serviceDesc.Streams[0], "/v1.ShopifyService/DataSync", opts...)
	if err != nil {
		return nil, err
	}
	x := &shopifyServiceDataSyncClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type ShopifyService_DataSyncClient interface {
	Recv() (*ShopifyDataSyncResponse, error)
	grpc.ClientStream
}

type shopifyServiceDataSyncClient struct {
	grpc.ClientStream
}

func (x *shopifyServiceDataSyncClient) Recv() (*ShopifyDataSyncResponse, error) {
	m := new(ShopifyDataSyncResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *shopifyServiceClient) DataSyncStreamClient(ctx context.Context, opts ...grpc.CallOption) (ShopifyService_DataSyncStreamClientClient, error) {
	stream, err := c.cc.NewStream(ctx, &_ShopifyService_serviceDesc.Streams[1], "/v1.ShopifyService/DataSyncStreamClient", opts...)
	if err != nil {
		return nil, err
	}
	x := &shopifyServiceDataSyncStreamClientClient{stream}
	return x, nil
}

type ShopifyService_DataSyncStreamClientClient interface {
	Send(*ShopifyDataSyncRequest) error
	CloseAndRecv() (*ShopifyDataSyncResponse, error)
	grpc.ClientStream
}

type shopifyServiceDataSyncStreamClientClient struct {
	grpc.ClientStream
}

func (x *shopifyServiceDataSyncStreamClientClient) Send(m *ShopifyDataSyncRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *shopifyServiceDataSyncStreamClientClient) CloseAndRecv() (*ShopifyDataSyncResponse, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(ShopifyDataSyncResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *shopifyServiceClient) DataSyncStreamBiDirectional(ctx context.Context, opts ...grpc.CallOption) (ShopifyService_DataSyncStreamBiDirectionalClient, error) {
	stream, err := c.cc.NewStream(ctx, &_ShopifyService_serviceDesc.Streams[2], "/v1.ShopifyService/DataSyncStreamBiDirectional", opts...)
	if err != nil {
		return nil, err
	}
	x := &shopifyServiceDataSyncStreamBiDirectionalClient{stream}
	return x, nil
}

type ShopifyService_DataSyncStreamBiDirectionalClient interface {
	Send(*ShopifyDataSyncRequest) error
	Recv() (*ShopifyDataSyncResponse, error)
	grpc.ClientStream
}

type shopifyServiceDataSyncStreamBiDirectionalClient struct {
	grpc.ClientStream
}

func (x *shopifyServiceDataSyncStreamBiDirectionalClient) Send(m *ShopifyDataSyncRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *shopifyServiceDataSyncStreamBiDirectionalClient) Recv() (*ShopifyDataSyncResponse, error) {
	m := new(ShopifyDataSyncResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ShopifyServiceServer is the server API for ShopifyService service.
type ShopifyServiceServer interface {
	// Shopify oauth
	Auth(context.Context, *ShopifyAuthRequest) (*Response, error)
	NoReturn(context.Context, *ShopifyAuthRequest) (*Empty, error)
	// Shopify after auth callback
	AuthCallback(context.Context, *ShopifyAuthCallbackRequest) (*Response, error)
	// Shopify data sync request stream server
	DataSync(*ShopifyDataSyncRequest, ShopifyService_DataSyncServer) error
	// Shopify data sync request steam client
	DataSyncStreamClient(ShopifyService_DataSyncStreamClientServer) error
	// Shopify data sync request stream bi-directional
	DataSyncStreamBiDirectional(ShopifyService_DataSyncStreamBiDirectionalServer) error
}

// UnimplementedShopifyServiceServer can be embedded to have forward compatible implementations.
type UnimplementedShopifyServiceServer struct {
}

func (*UnimplementedShopifyServiceServer) Auth(context.Context, *ShopifyAuthRequest) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Auth not implemented")
}
func (*UnimplementedShopifyServiceServer) NoReturn(context.Context, *ShopifyAuthRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NoReturn not implemented")
}
func (*UnimplementedShopifyServiceServer) AuthCallback(context.Context, *ShopifyAuthCallbackRequest) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AuthCallback not implemented")
}
func (*UnimplementedShopifyServiceServer) DataSync(*ShopifyDataSyncRequest, ShopifyService_DataSyncServer) error {
	return status.Errorf(codes.Unimplemented, "method DataSync not implemented")
}
func (*UnimplementedShopifyServiceServer) DataSyncStreamClient(ShopifyService_DataSyncStreamClientServer) error {
	return status.Errorf(codes.Unimplemented, "method DataSyncStreamClient not implemented")
}
func (*UnimplementedShopifyServiceServer) DataSyncStreamBiDirectional(ShopifyService_DataSyncStreamBiDirectionalServer) error {
	return status.Errorf(codes.Unimplemented, "method DataSyncStreamBiDirectional not implemented")
}

func RegisterShopifyServiceServer(s *grpc.Server, srv ShopifyServiceServer) {
	s.RegisterService(&_ShopifyService_serviceDesc, srv)
}

func _ShopifyService_Auth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ShopifyAuthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShopifyServiceServer).Auth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.ShopifyService/Auth",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShopifyServiceServer).Auth(ctx, req.(*ShopifyAuthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShopifyService_NoReturn_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ShopifyAuthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShopifyServiceServer).NoReturn(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.ShopifyService/NoReturn",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShopifyServiceServer).NoReturn(ctx, req.(*ShopifyAuthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShopifyService_AuthCallback_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ShopifyAuthCallbackRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShopifyServiceServer).AuthCallback(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.ShopifyService/AuthCallback",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShopifyServiceServer).AuthCallback(ctx, req.(*ShopifyAuthCallbackRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShopifyService_DataSync_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ShopifyDataSyncRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ShopifyServiceServer).DataSync(m, &shopifyServiceDataSyncServer{stream})
}

type ShopifyService_DataSyncServer interface {
	Send(*ShopifyDataSyncResponse) error
	grpc.ServerStream
}

type shopifyServiceDataSyncServer struct {
	grpc.ServerStream
}

func (x *shopifyServiceDataSyncServer) Send(m *ShopifyDataSyncResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _ShopifyService_DataSyncStreamClient_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ShopifyServiceServer).DataSyncStreamClient(&shopifyServiceDataSyncStreamClientServer{stream})
}

type ShopifyService_DataSyncStreamClientServer interface {
	SendAndClose(*ShopifyDataSyncResponse) error
	Recv() (*ShopifyDataSyncRequest, error)
	grpc.ServerStream
}

type shopifyServiceDataSyncStreamClientServer struct {
	grpc.ServerStream
}

func (x *shopifyServiceDataSyncStreamClientServer) SendAndClose(m *ShopifyDataSyncResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *shopifyServiceDataSyncStreamClientServer) Recv() (*ShopifyDataSyncRequest, error) {
	m := new(ShopifyDataSyncRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _ShopifyService_DataSyncStreamBiDirectional_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ShopifyServiceServer).DataSyncStreamBiDirectional(&shopifyServiceDataSyncStreamBiDirectionalServer{stream})
}

type ShopifyService_DataSyncStreamBiDirectionalServer interface {
	Send(*ShopifyDataSyncResponse) error
	Recv() (*ShopifyDataSyncRequest, error)
	grpc.ServerStream
}

type shopifyServiceDataSyncStreamBiDirectionalServer struct {
	grpc.ServerStream
}

func (x *shopifyServiceDataSyncStreamBiDirectionalServer) Send(m *ShopifyDataSyncResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *shopifyServiceDataSyncStreamBiDirectionalServer) Recv() (*ShopifyDataSyncRequest, error) {
	m := new(ShopifyDataSyncRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _ShopifyService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "v1.ShopifyService",
	HandlerType: (*ShopifyServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Auth",
			Handler:    _ShopifyService_Auth_Handler,
		},
		{
			MethodName: "NoReturn",
			Handler:    _ShopifyService_NoReturn_Handler,
		},
		{
			MethodName: "AuthCallback",
			Handler:    _ShopifyService_AuthCallback_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "DataSync",
			Handler:       _ShopifyService_DataSync_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "DataSyncStreamClient",
			Handler:       _ShopifyService_DataSyncStreamClient_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "DataSyncStreamBiDirectional",
			Handler:       _ShopifyService_DataSyncStreamBiDirectional_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "example.proto",
}
